@startuml
hide circle

abstract class Geometry {
    - pontos
    +__init__(pontos)
    +area(): float
}

class LineString {
    +area(): float
}

class Polygon {
    +area(): float
}

Geometry <|-- LineString
Geometry <|-- Polygon
@enduml
